### ISSUE TITLE
Master isn't deploying anymore

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/grafana-scalingo#19]
See https://my.agora-fr1.scalingo.com/apps/grafana-infra/deployments/8e80cd37-dd68-44ca-91d3-137cf0f3086c

**Comment by johnsudaar** [comment]
Contact https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/all/conversations/24333183861 when done

**Comment by johnsudaar** [comment]
Isn't that fixed by https://github.com/Scalingo/grafana-scalingo/pull/20 @Soulou ?

**Comment by EtienneM** [comment]
Yes it is
