### ISSUE TITLE
Change version number

### ISSUE THREAD

**Issue by lazybird** [Scalingo/grafana-scalingo#53]
Hey @brandon-welsch 

Thanks for the recent work on updating this repo.

I'm wondering if the version number is right. After using the current master, I still have `  "version": "7.5.0"` on /api/health.

Any idea ?
Anything to do with this line here ?

https://github.com/Scalingo/grafana-scalingo/blob/b29267f2f6ccf69325e559cf5f1d13895e31f495/pkg/cmd/grafana-server/main.go#L10

**Comment by Soulou** [comment]
Hi @lazybird 

The version problem is related how the go app is built.

Official grafana distribution is changing this at build time with custom build ags which are not compatible yet with Scalingo Golang build system.

We're trying to think of a method which would word, ourselves users of Grafana, we'd be glad seeing the right version ;-)

**Comment by lazybird** [comment]
Ok thanks for the message. 

So we can safely conclude that we are effectively running v8.3.2 and that the display is just not right for now...

Thanks again.

**Comment by Soulou** [comment]
Yes exactly!
