### ISSUE TITLE
Major upgrade to v10

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/grafana-scalingo#69]
https://grafana.com/blog/2023/06/13/grafana-10-release-all-the-new-features-to-know/
Breaking changes: https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v10-0/

It should be tackled after #68

**Comment by Frzk** [comment]
https://github.com/grafana/grafana/releases/tag/v10.0.2

**Comment by ipfaze** [comment]
https://github.com/grafana/grafana/releases/tag/v10.2.2

**Comment by Frzk** [comment]
https://github.com/grafana/grafana/releases/tag/v10.2.3
