### ISSUE TITLE
[Grafana] Upgrade from 10.2.3 to 10.4.3

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/grafana-scalingo#78]
https://github.com/grafana/grafana/releases/tag/v10.3.0
https://github.com/grafana/grafana/releases/tag/v10.3.1
https://github.com/grafana/grafana/releases/tag/v10.3.3

**Comment by EtienneM** [comment]
https://github.com/grafana/grafana/releases/tag/v10.3.4

**Comment by EtienneM** [comment]
https://github.com/grafana/grafana/releases/tag/v10.4.0

**Comment by Frzk** [comment]
https://github.com/grafana/grafana/releases/tag/v10.4.2

**Comment by EtienneM** [comment]
https://github.com/grafana/grafana/releases/tag/v10.4.3
